kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mautic.name" .}}-var-www-html
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mautic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size | quote }}
  storageClassName: {{ .Values.volume.storageClass | quote }}
    

